### ISSUE TITLE
Python version of 04-face-service.md needs update to use ImageAnalysisClient

### ISSUE THREAD

**Issue by rhabenbacher** [MicrosoftLearning/mslearn-ai-vision#10]
The instruction needs an update to use the newer `azure-ai-vision-imageanalysis` library instead of `azure-ai-vision` (Python code).

I propose the following updates for the Python code:

## Prepare to use the Azure AI Vision SDK
....
 **Python**

    ```
    pip install azure-ai-vision-imageanalysis
    ```

## Detect faces in an image

 **Python**

```Python 
from dotenv import load_dotenv
import os
from PIL import Image, ImageDraw
import sys

from matplotlib import pyplot as plt

# Import namespaces
from azure.ai.vision.imageanalysis import ImageAnalysisClient
from azure.core.credentials import AzureKeyCredential
from azure.ai.vision.imageanalysis.models import VisualFeatures




def main():
    global cv_client

    try:
        # Get Configuration Settings
        load_dotenv()
        ai_endpoint = os.getenv('AI_SERVICE_ENDPOINT')
        ai_key = os.getenv('AI_SERVICE_KEY')

        # Get image
        image_file = 'images/people.jpg'
        if len(sys.argv) > 1:
            image_file = sys.argv[1]

        # Authenticate Azure AI Vision client
        cv_client = ImageAnalysisClient(ai_endpoint, AzureKeyCredential(ai_key))    
        
        # Analyze image
        AnalyzeImage(image_file, cv_client)

    except Exception as ex:
        print(ex)


def AnalyzeImage(image_file, cv_client:ImageAnalysisClient):
    print('\nAnalyzing', image_file)

    
    # Get image analysis
    with open(image_file, "rb") as f:
        image_data = f.read()

    result = cv_client.analyze(image_data=image_data, visual_features= [
        VisualFeatures.PEOPLE
    ])
        

    # Get people in the image
    if result.people is not None:
        print("\nPeople in image:")
        
        # Prepare image for drawing
        image = Image.open(image_file)
        fig = plt.figure(figsize=(image.width/100, image.height/100))
        plt.axis('off')
        draw = ImageDraw.Draw(image)
        color = 'cyan'
        
        for detected_people in result.people.list:
            # Draw object bounding box if confidence > 50%
            if detected_people.confidence > 0.5:
                # Draw object bounding box
                r = detected_people.bounding_box
                bounding_box = ((r.x, r.y), (r.x + r.width, r.y + r.height))
                draw.rectangle(bounding_box, outline=color, width=3)
            
                # Return the confidence of the person detected
                print(" {} (confidence: {:.2f}%)".format(detected_people.bounding_box, detected_people.confidence * 100))
                    
        # Save annotated image
        plt.imshow(image)
        plt.tight_layout(pad=0)
        outputfile = 'detected_people.jpg'
        fig.savefig(outputfile)
        print('  Results saved in', outputfile)
    
    else:
        print(" Analysis failed.")

if __name__ == "__main__":
    main()


```

**Comment by kgbarnes91** [comment]
I'm noticing this issue right now as well since I'm using Python and I arrived at the same solution - use:
`pip install azure-ai-vision-imageanalysis`
or in my case using Python 3.12:
`pip3 install azure-ai-vision-imageanalysis`

From the exercise a couple modules before ("Analyze Images"; https://microsoftlearning.github.io/mslearn-ai-vision/Instructions/Exercises/01-analyze-images.html), the only difference between the SDK installation for the "Analyze Images" module exercise and this "Detect, analyze, and recognize faces" module is that in the C# command, there is a more updated version of the code in the "Analyze Images" module. I searched the PyPi.org database (since _pip search_ or _pip3 search_ is now a deprecated feature for the shell) for "azure-ai-vision" and the latest version to reference to install is the command you shared (Reference: https://pypi.org/project/azure-ai-vision-imageanalysis/).

**Comment by afelix-95** [comment]
The `azure-ai-vision` library still works for me, even though it's been updated to `azure-ai-vision-imageanalysis`. The updated code suggested above also produces the correct output.

**Comment by ivorb** [comment]
Thanks @afelix-95 I'll take this one on - they both still work just fine, but using the newer SDK will be the preferred end result

**Comment by GraemeMalcolm** [comment]
@ivorb, any progress on this? Can we close the issue?

**Comment by ivorb** [comment]
there's nothing broken, so this hasn't taken priority. Added to my backlog, closing this issue.

**Comment by GraemeMalcolm** [comment]
[like]  Graeme Malcolm reacted to your message:
________________________________
