### ISSUE TITLE
Lab "Analyze Video with Video Analyzer" - Link to Video Analyzer/indexer documentation is wrong

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/mslearn-ai-vision#15]
In the last paragraph of the instructions the link is not correct, and we see a 404 page. But I'm not sure what the intention of that link is, since this exercise is mixing the terms "Video Indexer" and "Video Analyzer"

Now:
For more information about Video Analyzer, see the [Video Analyzer documentation](https://docs.microsoft.com/azure/azure-video-analyzer/video-analyzer-for-media-docs/).

Should be:
For more information about Video Analyzer, see the [Video Analyzer documentation](https://learn.microsoft.com/azure/azure-video-analyzer/video-analyzer-docs/).

**Comment by ivorb** [comment]
fixed
