### ISSUE TITLE
Exercise "Extract custom entities" - clarification needed due to UI updates

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/mslearn-ai-vision#17]
In Step 2, when provisioning the resource, it should be clarified that the resource name is "Language" or "Language Service" and not "Azure AI Language Service", at least this is what the Azure Portal currently shows.

![image](https://github.com/MicrosoftLearning/mslearn-ai-vision/assets/37703728/33274847-d2e0-4592-8deb-0935b687e2da)

Additionally, the feature to enable custom classification is labeled under "custom features" as "Custom text classification, Custom named entity recognition, Custom summarization, Custom sentiment analysis & Custom Text Analytics for health" and there is no "asking about Additional features".
![image](https://github.com/MicrosoftLearning/mslearn-ai-vision/assets/37703728/23b054b9-a79b-4615-94ce-24c80ea443a4)

**Comment by ivorb** [comment]
this is the vision repo, it appears this is in the wrong place. Additionally, Azure AI is the area of Azure we're in for the first screenshot, so it follows that Language Service is the correct option.

I'll clarify the custom options
