### ISSUE TITLE
Custom models in 02-image-classification fail due to dataset corruption

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/mslearn-ai-vision#18]
#### Navigate to Custom models on the left, and select Train a new model. Use the following settings:

    Name of model: classifyfruit
    Model type: Image classification
    Choose training dataset: training_images
    Leave the rest as default, and select Train model

This fails immediately due to dataset corruption [p1].

[p1]

![image](https://github.com/MicrosoftLearning/mslearn-ai-vision/assets/94069201/f7ae11d2-ae3e-4f48-8c45-981d90b6fa50)

**Comment by ivorb** [comment]
Can't reproduce, reached out to author for more information

**Comment by ivorb** [comment]
verified no repro with author
