### ISSUE TITLE
Wrong example code - Lab02 Face Detection

### ISSUE THREAD

**Issue by felipementel** [MicrosoftLearning/mslearn-ai-vision#23]
There is a piece of code that is in the laboratory that is wrong for the C# language as shown in print.

![image](https://github.com/MicrosoftLearning/mslearn-ai-vision/assets/14238257/8f16d7f8-6577-4638-ac16-9179e2ecc61d)

With this error, the application cannot be compiled, generating a terrible experience for the user

**Comment by GraemeMalcolm** [comment]
This is an error in the lab hosting environment, not the content (it's rendering the "<" as encoded HTML). We'll raise it with the lab hoster.
