### ISSUE TITLE
Image Analysis Lab Readme files are not sync with Azure.AI.Vision.ImageAnalysis 1.0.0-beta.1 sdk.

### ISSUE THREAD

**Issue by moirf** [MicrosoftLearning/mslearn-ai-vision#6]
I tried to follow this - https://github.com/MicrosoftLearning/mslearn-ai-vision/blob/main/Instructions/Exercises/01-analyze-images.md, but the namespace 'Azure.AI.Vision.Common' not resolving with Azure.AI.Vision.ImageAnalysis 1.0.0-beta.1 sdk, and hence not able to complete the exercise.
Can you please update?

**Comment by ivorb** [comment]
This has now been addressed to use beta.1
